### ISSUE TITLE
alliance -  Attacks 

### ISSUE THREAD

**Issue by Sonikboy** [iSparkas/Dboor-Updated-V1.0#3]
alliance.php?t=2

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

Deprecated: Non-static method ReportHelper::getReportResultRelative() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 507

Deprecated: Non-static method ReportHelper::getReportResultText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 508

admin
Deprecated: Non-static method ReportHelper::getReportActionText() should not be called statically, assuming $this from incompatible context in C:\xampp\htdocs\app\view\alliance.phtml on line 523
Sicks Ali

**Comment by iSparkas** [comment]
Here is more non-static methods errors. 
I will fix it asap.
