### ISSUE TITLE
social network

### ISSUE THREAD

**Issue by Sonikboy** [iSparkas/Dboor-Updated-V1.0#4]
snprofile.php?uid=1

Notice: Constant LANGUI_PROFILE_T1 already defined in C:\xampp\htdocs\app\lang\en\ui\snprofile.php on line 4

Notice: Constant LANGUI_PROFILE_T1 already defined in C:\xampp\htdocs\app\lang\en\ui\snprofile.php on line 5

NOTICE: USE OF UNDEFINED CONSTANT LANGUI_PROFILE_T3 - ASSUMED 'LANGUI_PROFILE_T3' IN C:\XAMPP\HTDOCS\APP\VIEW\SNPROFILE.PHTML ON LINE 148

NOTICE: USE OF UNDEFINED CONSTANT LANGUI_PROFILE_T4 - ASSUMED 'LANGUI_PROFILE_T4' IN C:\XAMPP\HTDOCS\APP\VIEW\SNPROFILE.PHTML ON LINE 156

**Comment by iSparkas** [comment]
Don't even see a point of having this feature in server. disabled it.
